
const MOVE_SPEED = 120;
const JUMP_FORCE = 360;
const BIG_JUMP_FORCE = 800;
const FALL_DEATH = 400;
const ENEMY_SPEED = 20;
export { MOVE_SPEED, JUMP_FORCE, BIG_JUMP_FORCE, FALL_DEATH, ENEMY_SPEED };